name: bytes_dicom
description: A package that adds DICOM methods to the _bytes_ package.
version: 0.7.0
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/bytes

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  bytes:
    path: C:/odw/sdk/bytes
    version: ^0.7.6
  constants:
    path: ../../constants
    version: ^0.7.6

dev_dependencies:
  benchmark_harness: any
  coverage: any
  grinder: ^0.8.0
  test:  any
  test_tools:
    path: C:/odw/test_tools
    version: ^0.7.5
  rng:
    path: C:/odw/sdk/rng
    version: ^0.8.0
